# task settings
robot_name: s500_uam
trajectory_name: catch_vicon

dt_traj_opt: 10
simulation_time: 10
use_squash: true
yaml_path: config/yaml

# Timing parameters
simulation_dt: 0.001  # seconds - simulation time step (1ms)
control_dt: 0.01      # seconds - control time step (20ms)

initial_state: [-1.5, 0, 1.5, 0, 0, 0, 1, -1.2, -0.6, 0, 0, 0, 0, 0, 0, 0, 0]

results_dir: results/numeric_sim
save_results: false
plot_results: true

enable_disturbance: true
disturbance_start_time: 3.0
disturbance_force: [1.0, 0.5, 10.0]
disturbance_torque: [0.2, 0.0, 0.0]
disturbance_torque_arm: [0.2, 0.0]

# Joint sin disturbance parameters
enable_joint_sin_disturbance: false
joint_sin_amplitude: [0.02, 0.00]  # amplitude for joint1, joint2 (Nm)
joint_sin_frequency: [0.2, 0.2]   # frequency for joint1, joint2 (Hz)

enable_noise: false
state_noise_std: 0.0001

enable_l1_control: true
l1_start_time: 0
l1_as_coef: -0.01
l1_filter_time_constant: [0.1, 0.1, 0.01]
l1_version: v2