gazebo_ros_control:
  pid_gains:
    joint_1:
      p: 10.0
      i: 0.0
      d: 0.0
    joint_2:
      p: 10.0
      i: 0.0
      d: 0.0
    joint_3:
      p: 10.0
      i: 0.0
      d: 0.0
    joint_4:
      p: 10.0
      i: 0.0
      d: 0.0

# Controller configs (if any)
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 500

joint_1_controller:
  type: velocity_controllers/JointVelocityController
  joint: joint_1
  # gains:
  #   p: 100.0  # 比例增益
  #   i: 1.0    # 积分增益
  #   d: 10.0   # 微分增益

joint_2_controller:
  type: velocity_controllers/JointVelocityController
  joint: joint_2
  # gains:
  #   p: 100.0
  #   i: 1.0
  #   d: 10.0

joint_3_controller:
  type: position_controllers/JointPositionController
  joint: joint_3

joint_4_controller:
  type: position_controllers/JointPositionController
  joint: joint_4
