# dynamixel_control.yaml
controller_manager:
  ros__parameters:
    update_rate: 100.0  # 控制器更新频率

dynamixel_controller:
  type: "dynamixel_controllers/JointPositionController"
  joint: "joint_1"  # 舵机的名称
  pid:  # PID 控制器参数
    p: 100.0
    i: 0.0
    d: 10.0