joint:
  names: [joint_1, joint_2]
motion:
  names: [right, zero, left]
  right:
    step: [0.0, -1.9]  # radian
    time_from_start: 1.0  # sec
  zero:
    step: [0.0, 0.0]
    time_from_start: 2.0
  left:
    step: [0.0, 1.6]
    time_from_start: 3.0

