mpc_controller:
  robot:
    name: "s500"
    urdf: "models/urdf/s500_simple.urdf"
    follow: "config/yaml/multicopter/s500.yaml"

  integration_method: "IntegratedActionModelEuler"
  knots: 20
  solver: "SolverSbFDDP"
  iters: 10
  dt: 50

  carrot_weight: 1000
  carrot_tail_weight: 1
  carrot_tail_act_weights: [1000, 1000, 1000, 1, 1, 1, 1, 1, 1, 1, 1, 1]
  carrot_control_reg_weight: 1e-1
  carrot_control_reg_act_weights: [1, 1, 1, 1]
  carrot_state_reg_weight: 1e-2
  carrot_state_ref_act_weights: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
  carrot_state_limits_weight: 10
  carrot_state_limits_act_weights: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
  carrot_state_limits_u_bound: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
  carrot_state_limits_l_bound: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

  rail_weight: 100
  rail_activation_weights: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

  rail_control_weight: 0
  control_reference: [5, 5, 5, 5]

  rail_state_limits_weight: 0
  rail_state_limits_act_weights: [0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1]
  rail_state_limits_u_bound: [0, 0, 0, 0, 0, 0, 0.5, 0.5, 0.5, 1, 1, 1]
  rail_state_limits_l_bound: [0, 0, 0, 0, 0, 0, -0.5, -0.5, -0.5, -1, -1, -1]
