trajectory:
  robot:
    name: "s500_uam"
    urdf: "models/urdf/s500_uam_simple.urdf"
    follow: "config/yaml/multicopter/s500.yaml"

  initial_state: [-1.5, 0, 1.5, 0, 0, 0, 1, -1.2, -0.6, 0, 0, 0, 0, 0, 0, 0, 0]

  stages:
    - name: "approach"
      duration: 3000 #ms
      transition: true
      costs:
        - name: "state_reg"
          type: "ResidualModelState"
          weight: 1
          reference: [0, 0, 1.1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
          activation: "ActivationModelWeightedQuad"
          weights: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

        - name: "state_limits"
          type: "ResidualModelState"
          weight: 10
          activation: "ActivationModelWeightedQuadraticBarrier"
          weights: [0, 0, 0, 0, 0, 0, 10, 10, 1, 1, 1, 1, 1, 1, 10, 10]
          u_bound: [0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0.5, 0.5]
          l_bound: [0, 0, 0, 0, 0, 0, -1, -1, -1, -1, -1, -1, -1, -1, -0.5, -0.5]

        - name: "control_reg"
          type: "ResidualModelControl"
          weight: 1
          reference: [5, 5, 5, 5, 0, 0]
          activation: "ActivationModelWeightedQuad"
          weights: [1, 1, 1, 1, 1, 1]

    - name: "pre_grasp"
      duration: 0  #ms
      costs:
        - name: "state_quadrotor"
          type: "ResidualModelState"
          weight: 1
          reference: [0, 0, 1.1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]  # note the reference attitude using quaternion
          activation: "ActivationModelWeightedQuad"
          weights: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

        - name: "reg_control"
          type: "ResidualModelControl"
          weight: 1
          reference: [5, 5, 5, 5, 0, 0]
          activation: "ActivationModelWeightedQuad"
          weights: [1, 1, 1, 1, 10, 10]

    - name: "grasp"
      duration: 500 #ms
      transition: true
      costs:
        - name: "state_reg"
          type: "ResidualModelState"
          weight: 1e-2
          reference: [0, 0, 1.2, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
          activation: "ActivationModelWeightedQuad"
          weights: [1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0]

        - name: "state_limits"
          type: "ResidualModelState"
          weight: 10
          activation: "ActivationModelWeightedQuadraticBarrier"
          weights: [0, 0, 0, 0, 0, 0, 10, 10, 1, 1, 1, 1, 1, 1, 10, 10]
          u_bound: [0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0.5, 0.5]
          l_bound: [0, 0, 0, 0, 0, 0, -1, -1, -1, -1, -1, -1, -1, -1, -0.5, -0.5]

        - name: "control_reg"
          type: "ResidualModelControl"
          weight: 100
          reference: [5, 5, 5, 5, 0, 0]
          activation: "ActivationModelWeightedQuad"
          weights: [1, 1, 1, 1, 1000, 1000]

        - name: "translation_ee"
          type: "ResidualModelFrameTranslation"
          weight: 1000
          link_name: "gripper_link"
          position: [0.0, 0, 0.8]

        - name: "motion_ee"
          type: "ResidualModelFrameVelocity"
          weight: 100
          link_name: "gripper_link"
          activation: "ActivationModelWeightedQuad"
          weights: [1, 1, 1, 0, 0, 0]
          linear: [0, 0, 0]
          angular: [0, 0, 0]

    - name: "move_away"
      duration: 3000 #ms
      transition: true
      costs:
        - name: "state_reg"
          type: "ResidualModelState"
          weight: 1
          reference: [0, 0, 1.5, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0]
          activation: "ActivationModelWeightedQuad"
          weights: [1, 1, 1, 1, 1, 1, 10, 10, 1, 1, 1, 1, 1, 1, 10, 10]

        - name: "state_limits"
          type: "ResidualModelState"
          weight: 10
          activation: "ActivationModelWeightedQuadraticBarrier"
          weights: [0, 0, 0, 0, 0, 0, 10, 10, 1, 1, 1, 1, 1, 1, 10, 10]
          u_bound: [0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0.5, 0.5]
          l_bound: [0, 0, 0, 0, 0, 0, -1, -1, -1, -1, -1, -1, -1, -1, -0.5, -0.5]

        - name: "control_reg"
          type: "ResidualModelControl"
          weight: 1
          reference: [5, 5, 5, 5, 0, 0]
          activation: "ActivationModelWeightedQuad"
          weights: [1, 1, 1, 1, 100, 100]

        # - name: "motion_ee"
        #   type: "ResidualModelFrameVelocity"
        #   weight: 100
        #   link_name: "gripper_link"
        #   activation: "ActivationModelWeightedQuad"
        #   weights: [1, 1, 1, 0, 0, 0]
        #   linear: [0, 0, 0]
        #   angular: [0, 0, 0]

    - name: "hover_after_grasp"
      duration: 0 #ms
      costs:
        - name: "state_all"
          type: "ResidualModelState"
          weight: 1000
          reference: [1.5, 0, 1.5, 0, 0, 0, 1, -1.2, -0.6, 0, 0, 0, 0, 0, 0, 0, 0]
          activation: "ActivationModelWeightedQuad"
          weights: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

        # - name: "placement_base_link"
        #   type: "ResidualModelFramePlacement"
        #   weight: 2000
        #   link_name: "base_link"
        #   position: [3.0, 0, 1.5]
        #   orientation: [0, 0, 0, 1] # x,y,z,w

        # - name: "motion_base_link"
        #   type: "ResidualModelFrameVelocity"
        #   weight: 6000
        #   link_name: "base_link"
        #   linear: [0, 0, 0]
        #   angular: [0, 0, 0]

        # - name: "motion_grasp"
        #   type: "ResidualModelFrameVelocity"
        #   weight: 1000
        #   link_name: "link_3"
        #   linear: [0, 0, 0]
        #   angular: [0, 0, 0]

        - name: "reg_control"
          type: "ResidualModelControl"
          weight: 0.1
          reference: [5, 5, 5, 5, 0, 0]
          activation: "ActivationModelWeightedQuad"
          weights: [1, 1, 1, 1, 100, 100]

      
      