trajectory:
  robot:
    name: "s500_uam"
    urdf: "/home/helei/catkin_eagle_mpc/src/eagle_mpc_debugger/models/urdf/s500_uam_simple.urdf"
    follow: "/home/helei/catkin_eagle_mpc/src/eagle_mpc_debugger/config/yaml/multicopter/s500.yaml"

  initial_state: [-1.5, 0, 1.5, 0, 0, 0, 1, -1.2, -0.7, 0, 0, 0, 0, 0, 0, 0, 0]

  stages:
    - name: "initial_state"
      duration: 1000 #ms
      transition: true
      costs:
        - name: "state_reg"
          type: "ResidualModelState"
          weight: 5000  # 使用较大的权重
          reference: [-1.5, 0, 1.5, 0, 0, 0, 1, -1.2, -0.7, 0, 0, 0, 0, 0, 0, 0, 0]  # 与initial_state完全一致
          activation: "ActivationModelWeightedQuad"
          weights: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

    - name: "approach"
      duration: 3000 #ms
      transition: false
      costs:
        - name: "state_reg"
          type: "ResidualModelState"
          weight: 1
          reference: [0, 0, 1.1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
          activation: "ActivationModelWeightedQuad"
          weights: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

        - name: "state_limits"
          type: "ResidualModelState"
          weight: 10
          reference: [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
          activation: "ActivationModelWeightedQuadraticBarrier"
          weights: [0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 100, 100]
          u_bound: [0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1]
          l_bound: [0, 0, 0, 0, 0, 0, -1, -1, -1, -1, -1, 0, 0, 0, -1, -1]

        - name: "control_reg"
          type: "ResidualModelControl"
          weight: 10
          reference: [5, 5, 5, 5, 0, 0]
          activation: "ActivationModelWeightedQuad"
          weights: [1, 1, 1, 1, 1, 1]

    # - name: "pre_grasp"
    #   duration: 0 #ms
    #   costs:
    #     - name: "state_quadrotor"
    #       type: "ResidualModelState"
    #       weight: 100
    #       reference: [0, 0, 1.1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    #       activation: "ActivationModelWeightedQuad"
    #       weights: [1, 1, 1, 1, 1, 1, 10, 10, 0, 0, 0, 0, 0, 0, 0, 0]

    #     - name: "reg_control"
    #       type: "ResidualModelControl"
    #       weight: 1
    #       reference: [5, 5, 5, 5, 0, 0]
    #       activation: "ActivationModelWeightedQuad"
    #       weights: [1, 1, 1, 1, 10, 10]

    - name: "grasp"
      duration: 1000 #ms
      costs:
        - name: "state_reg"
          type: "ResidualModelState"
          weight: 10
          reference: [0, 0, 1.2, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
          activation: "ActivationModelWeightedQuad"
          weights: [1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0]

        - name: "state_limits"
          type: "ResidualModelState"
          weight: 10
          reference: [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
          activation: "ActivationModelWeightedQuadraticBarrier"
          weights: [0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1]
          u_bound: [0, 0, 0, 0, 0, 0, 1.9, 1.9, 0, 0, 0, 0, 0, 0, 3, 3]
          l_bound:
            [0, 0, 0, 0, 0, 0, -1.9, -1.9, 0, 0, 0, 0, 0, 0, -3, -3]

        - name: "control_reg"
          type: "ResidualModelControl"
          weight: 1e-2
          reference: [5, 5, 5, 5, 0, 0]
          activation: "ActivationModelWeightedQuad"
          weights: [1, 1, 1, 1, 1, 1]

        - name: "translation_ee"
          type: "ResidualModelFrameTranslation"
          weight: 1000
          link_name: "gripper_link"
          position: [0.0, 0, 0.8]

        - name: "motion_ee"
          type: "ResidualModelFrameVelocity"
          weight: 100
          link_name: "gripper_link"
          activation: "ActivationModelWeightedQuad"
          weights: [1, 1, 1, 0, 0, 0]
          linear: [0, 0, 0]
          angular: [0, 0, 0]

    - name: "move_away"
      duration: 3000 #ms
      transition: true
      costs:
        - name: "state_reg"
          type: "ResidualModelState"
          weight: 1e-1
          reference: [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
          activation: "ActivationModelWeightedQuad"
          weights: [1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1]

        - name: "state_limits"
          type: "ResidualModelState"
          weight: 10
          reference: [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
          activation: "ActivationModelWeightedQuadraticBarrier"
          weights: [0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 100, 100]
          u_bound: [0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1]
          l_bound: [0, 0, 0, 0, 0, 0, -1, -1, 0, 0, 0, 0, 0, 0, -1, -1]

        - name: "control_reg"
          type: "ResidualModelControl"
          weight: 5e-2
          reference: [0, 0, 0, 0, 0, 0]
          activation: "ActivationModelWeightedQuad"
          weights: [1, 1, 1, 1, 0, 0]

    - name: "hover_after_grasp"
      duration: 0 #ms
      costs:
        - name: "state_arm"
          type: "ResidualModelState"
          weight: 100
          reference: [1.5, 0, 1.5, 0, 0, 0, 1, -1.2, -0.6, 0, 0, 0, 0, 0, 0, 0, 0]
          activation: "ActivationModelWeightedQuad"
          weights: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

        - name: "reg_control"
          type: "ResidualModelControl"
          weight: 5e-1
          reference: [0, 0, 0, 0, 0, 0]
          activation: "ActivationModelWeightedQuad"
          weights: [1, 1, 1, 1, 100, 100]

      